# This workflow integrates ShiftLeft Inspect with GitHub
# Visit https://docs.shiftleft.io for help
name: Analyze with ShiftLeft Inspect on Windows

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - master
      - feature/*
      - fix/*
  pull_request:
    branches:
      - master

jobs:
  Inspect-Win-Build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download ShiftLeft cli
      run: |
        Invoke-WebRequest -Uri 'https://cdn.shiftleft.io/download/sl-latest-windows-x64.zip' -OutFile sl.zip
        Expand-Archive -Path sl.zip -DestinationPath .

    # ShiftLeft requires Java 1.8. Post the package step override the version
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
    - name: Analyze with Inspect
      run: .\sl analyze --no-diagnostic --force --app ShiftLeftTSWin --tag branch=${GITHUB_REF} --js --cpg . -- --transpiling
      env:
        SHIFTLEFT_ORG_ID: ${{ secrets.SHIFTLEFT_ORG_ID }}
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
